In [2]:
import numpy as np
U =    np.array(
    [[1,2,6,-1],
    [0,3,1,0],
    [0,0,4,-1],
    [0,0,0,2] ])

b = np.array([-1,-3,-2,4]


 )


<img src="lu.png"><img>

In [51]:
def back_substituion(A,b):
    dim_x = b.size
    n = int(np.sqrt(U.size))
    x = np.zeros(dim_x)
    assert(dim_x == n)
    for k in range(n,0,-1):
        k -= 1
        sum = 0
        # print(k)
        for j in range(k+1,n):
            sum += A[k][j]*x[j]
        x[k] =  (b[k]-sum)/ A[k][k]
    return x
        
        

In [53]:
back_substituion(U,b)

3
2
3
1
2
3


array([ 3., -1.,  0.,  2.])

In [31]:
np.linalg.solve(U,b)

array([ 3., -1.,  0.,  2.])

In [52]:
[k for k in range(4,0,-1)]


[4, 3, 2, 1]

![Alt text](image.png)

In [123]:
def lu(A):
    n = np.sqrt(np.size(A))
    n = int(n)
    L = np.identity(n)
    U = np.zeros((n,n))
    for i in range(0,n):
        for j in range(0,n):
            if j < i:
                sum = 0
                if U[j][j] < 10**(-8): raise ValueError("ZeroDivisionError")
                for k in range(0,j):
                    sum += L[i][k] * U[k][j]
                L[i][j] = 1/U[j][j]*(A[i][j] - sum)
            else:
                sum2 = 0
                for k in range(0,i):
                    sum2 += L[i][k]*U[k][j]
                U[i][j] = A[i][j] -sum2

    return(L,U)
    

In [124]:
A = [[6,2,1,-1],[2,4,1,0],[1,1,4,-1],[-1,0,-1,3]]
lu(A)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.33333333,  1.        ,  0.        ,  0.        ],
        [ 0.16666667,  0.2       ,  1.        ,  0.        ],
        [-0.16666667,  0.1       , -0.24324324,  1.        ]]),
 array([[ 6.        ,  2.        ,  1.        , -1.        ],
        [ 0.        ,  3.33333333,  0.66666667,  0.33333333],
        [ 0.        ,  0.        ,  3.7       , -0.9       ],
        [ 0.        ,  0.        ,  0.        ,  2.58108108]]))

In [101]:
(lu(A)[0] @ lu(A)[1]).round()

array([[ 6.,  2.,  1., -1.],
       [ 2.,  4.,  1.,  0.],
       [ 1.,  1.,  4., -1.],
       [-1.,  0., -1.,  3.]])

In [82]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
[k for k in range(0,1)]

[0]

In [68]:
"""6 2 1 −1
2 4 1 0
1 1 4 −1
−1 0 −1 3""".replace(" ",",").replace("−","-").replace("\n","],[")

'6,2,1,-1],[2,4,1,0],[1,1,4,-1],[-1,0,-1,3'

In [ ]:
for i in range(0,n):
    for j in range(0,n):
        if j < i:
            sum = 0
            for k in range(1,j):
                sum += L[i][k] * U[k][j]
            L[i][j] = 1/U[i][j]*(A[i][j] - sum)
        else:
            sum2 = 0
            for k in range(1,i):
                sum2 += L[i][k]*U[k][j]
            U[i][j] = A[i][j] -sum2
            

In [62]:
L = np.zeros((3,3))
L                                               

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
[k for k in range(1,2)]

[1]

In [63]:
    for (i = 0;i < n;i++) {
        for (j = 0;j < m;j++) {
            for(k = 0; k < p; k++){
                A[i][j][k] = i + j + p;
                printf("%d,%d,%d, %d\n",i,j,k,i+j+k);
            }
        }
    }

SyntaxError: invalid syntax (3789193063.py, line 1)