In [3]:
from sklearn.linear_model import LinearRegression
import numpy as np

<img src="beispiel.PNG"><img>

In [4]:
x1=np.array([1,1,1])
x2=np.array([1,2,2])
x3=np.array([1,3,3])
x4=np.array([1,4,5])
x5=np.array([1,4,6])

In [5]:
X = np.array([x1,x2,x3,x4,x5])
y=np.array([2,1.5,4,2,5])


In [6]:
X.T @ y

array([14.5, 45. , 57. ])

In [7]:
np.linalg.solve(X.T @ X,X.T@y)

array([ 1.75, -0.5 ,  0.75])

In [8]:
linear_regression = LinearRegression()
linear_regression.fit(X,y)

LinearRegression()

In [9]:
linear_regression.coef_


array([ 0.  , -0.5 ,  0.75])

In [10]:
linear_regression.intercept_

1.7500000000000016

In [11]:
linear_regression.predict(X)

array([2.  , 2.25, 2.5 , 3.5 , 4.25])