In [2]:
from sklearn.linear_model import LinearRegression
import numpy as np

<img src="beispiel.PNG"><img>

In [3]:
x1=np.array([1,1,1])
x2=np.array([1,2,2])
x3=np.array([1,3,3])
x4=np.array([1,4,5])
x5=np.array([1,4,6])

In [4]:
X = np.array([x1,x2,x3,x3,x4])
y=np.array([2,1.5,4,2,5])


In [6]:
X.T @ y

array([14.5, 43. , 48. ])

In [7]:
np.linalg.solve(X.T @ X,X.T@y)

array([ 1.04545455, -1.        ,  1.59090909])

In [8]:
linear_regression = LinearRegression()
linear_regression.fit(X,y)

LinearRegression()

In [13]:
linear_regression.coef_


array([ 0.        , -1.        ,  1.59090909])

In [12]:
linear_regression.intercept_

1.0454545454545463

In [10]:
linear_regression.predict(X)

array([1.63636364, 2.22727273, 2.81818182, 2.81818182, 5.        ])